version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - fullstack-net
    restart: always

  frontend:
    image: mangesh1508/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    networks:
      - fullstack-net
    restart: always

  backend:
    image: mangesh1508/backend:latest
    container_name: backend
    networks:
      - fullstack-net
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fullstack-net
    restart: always

volumes:
  mongo_data:

networks:
  fullstack-net:
    driver: bridge

