version: "3.9"

services:
  frontend:
    image: mangesh1508/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fullstack-net
    restart: always
  backend:
    image: mangesh1508/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/appdb
    depends_on:
      - mongodb
    networks:
      - fullstack-net
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fullstack-net
    restart: always

volumes:
  mongo_data:

networks:
  fullstack-net:
    driver: bridge
